// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jczqeywzwjcsqybdrhrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjenFleXd6d2pjc3F5YmRyaHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU4NTEsImV4cCI6MjA2NTU4MTg1MX0.5EAajsmvZQ8U-N_CypI1wGczNvkGYvce1BbbEuD-yuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);